/** Reviewed presentation copy. Canonical evidence and original messages remain unchanged. */
const copy: Record<string, string> = {
  'Is growth concentrated in one business segment? Sectors does not expose segment data.': 'Apakah pertumbuhan terkonsentrasi pada satu segmen bisnis? Sectors tidak menyediakan data segmen.',
  'Did one-off items (asset sales, provisions released) lift net income? Not identifiable from summary financials.': 'Apakah pos tidak rutin, seperti penjualan aset atau pelepasan provisi, meningkatkan laba bersih? Hal ini tidak dapat diidentifikasi dari ringkasan keuangan.',
  'Latest-quarter revenue growth YoY': 'Pertumbuhan pendapatan kuartal terakhir dibanding tahun sebelumnya',
  'Latest-quarter net income growth YoY': 'Pertumbuhan laba bersih kuartal terakhir dibanding tahun sebelumnya',
  'Last fiscal year net income growth': 'Pertumbuhan laba bersih tahun fiskal terakhir',
  'Net margin change YoY': 'Perubahan margin bersih dibanding tahun sebelumnya',
  'ROE change vs prior 3-year average': 'Perubahan ROE dibanding rata-rata tiga tahun sebelumnya',
  'P/E versus peer median': 'P/E dibanding median pembanding',
  'ROE versus peer median': 'ROE dibanding median pembanding',
  'P/E versus own history': 'P/E dibanding riwayat perusahaan',
  'Will the payout policy continue? Future dividends are not knowable from reported data.': 'Apakah kebijakan pembayaran dividen akan berlanjut? Dividen masa depan tidak dapat diketahui dari data yang dilaporkan.',
  'Is the market pricing in risks not visible in reported numbers (asset quality, regulation)? Not testable with Sectors data.': 'Apakah harga pasar mencerminkan risiko yang tidak terlihat dalam angka laporan, seperti kualitas aset atau regulasi? Hal ini tidak dapat diuji dengan data Sectors.',
  'target company': 'perusahaan yang diperiksa',
  'different subsector': 'subsektor berbeda',
  'incompatible business model': 'model bisnis tidak sebanding',
  'metric unavailable': 'metrik tidak tersedia',
  'non-positive metric value is not comparable': 'metrik nol atau negatif tidak dapat dibandingkan',
  'period mismatch': 'periode tidak sesuai',
  'unknown': 'tidak diketahui',
  'No eligible checks remain.': 'Tidak ada pemeriksaan yang dapat dijalankan lagi.',
  'TIMEOUT': 'batas waktu tercapai',
  'BUDGET_EXHAUSTED': 'batas pemeriksaan tercapai',
  'UNOBTAINABLE': 'bukti tidak dapat diperoleh',
  'OUT_OF_SCOPE': 'di luar cakupan',
  'SUFFICIENT': 'bukti sudah cukup',
  'ERROR': 'terjadi kendala',
  'Is revenue actually growing?': 'Apakah pendapatan benar-benar tumbuh?',
  'Does net income growth confirm the revenue picture?': 'Apakah pertumbuhan laba bersih sejalan dengan pertumbuhan pendapatan?',
  'Did the last full financial year grow too, or is this only a good quarter?': 'Apakah tahun keuangan terakhir juga tumbuh, atau hanya kuartal ini yang bagus?',
  'Is growth slowing down compared with the previous quarter?': 'Apakah pertumbuhan melambat dibanding kuartal sebelumnya?',
  'Are profits keeping up with revenue?': 'Apakah pertumbuhan laba mengimbangi pendapatan?',
  'Did the profit margin shrink?': 'Apakah margin laba menyusut?',
  'Is the dividend yield actually high?': 'Apakah yield dividen benar-benar tinggi?',
  'Is the yield high by this company’s own standards?': 'Apakah yield tinggi dibanding riwayat perusahaan ini?',
  'Is the dividend still being paid?': 'Apakah dividen masih dibayarkan?',
  'Was the latest dividend a one-off?': 'Apakah dividen terakhir merupakan pembayaran yang tidak rutin?',
  'Is the company paying out more than it earns?': 'Apakah dividen yang dibayarkan melebihi laba perusahaan?',
  'Is there a usable P/E to compare at all?': 'Apakah tersedia P/E yang layak dibandingkan?',
  'Are there enough comparable peers to form a baseline?': 'Apakah jumlah perusahaan pembanding cukup untuk membentuk acuan?',
  'Is the P/E actually below the peer median?': 'Apakah P/E benar-benar di bawah median perusahaan pembanding?',
  'Does price-to-book agree that it is cheap?': 'Apakah P/BV juga menunjukkan valuasi murah?',
  'Is this growth a rebound from a weak prior year rather than new strength?': 'Apakah pertumbuhan ini merupakan pemulihan dari tahun sebelumnya yang lemah, bukan kekuatan baru?',
  'Is profit growing much faster than revenue, so the business itself is not growing as fast as earnings suggest?': 'Apakah laba tumbuh jauh lebih cepat dari pendapatan, sehingga pertumbuhan bisnis tidak sekuat pertumbuhan labanya?',
  'Is return on equity falling even while profit grows?': 'Apakah ROE turun meskipun laba tumbuh?',
  'Did the yield rise mostly because the share price fell, not because the dividend grew?': 'Apakah kenaikan yield terutama disebabkan harga saham yang turun, bukan dividen yang tumbuh?',
  'Is the company paying out almost all of its earnings, leaving little room to keep the dividend up?': 'Apakah perusahaan membagikan hampir seluruh labanya sehingga ruang untuk mempertahankan dividen terbatas?',
  'Is it cheaper because it earns lower returns on equity than its peers?': 'Apakah valuasinya lebih murah karena ROE lebih rendah dari perusahaan pembanding?',
  'Is this P/E normal for this company, so it is not cheap by its own standards?': 'Apakah P/E ini normal bagi perusahaan ini sehingga tidak murah dibanding riwayatnya sendiri?',
  'Does the low valuation coincide with a large fall in the share price?': 'Apakah valuasi rendah terjadi bersamaan dengan penurunan besar harga saham?',
  'Latest-quarter revenue growth, same quarter year-on-year': 'Pertumbuhan pendapatan kuartal terakhir dibanding kuartal yang sama tahun sebelumnya',
  'Latest-quarter net income growth, same quarter year-on-year': 'Pertumbuhan laba bersih kuartal terakhir dibanding kuartal yang sama tahun sebelumnya',
  'Last full fiscal year net income growth': 'Pertumbuhan laba bersih tahun fiskal terakhir',
  'Last full fiscal year revenue growth': 'Pertumbuhan pendapatan tahun fiskal terakhir',
  'Revenue growth trend versus the prior quarter (deceleration check)': 'Tren pertumbuhan pendapatan dibanding kuartal sebelumnya (pemeriksaan perlambatan)',
  'Earnings growth versus revenue growth (divergence check)': 'Pertumbuhan laba dibanding pendapatan (pemeriksaan perbedaan pertumbuhan)',
  'Net margin change year-on-year (deterioration check)': 'Perubahan margin bersih dibanding tahun sebelumnya (pemeriksaan penurunan)',
  'Prior fiscal year net income growth (base effect)': 'Pertumbuhan laba bersih tahun fiskal sebelumnya (efek basis)',
  'Net income growth minus revenue growth, latest quarter': 'Selisih pertumbuhan laba bersih dan pendapatan pada kuartal terakhir',
  'Latest fiscal year ROE versus its average over the prior three years': 'ROE tahun fiskal terakhir dibanding rata-rata tiga tahun sebelumnya',
  'Trailing dividend yield': 'Yield dividen 12 bulan terakhir',
  'Yield versus own historical average yield': 'Yield dibanding rata-rata riwayat yield perusahaan',
  'Time since the latest dividend payment (recency check)': 'Waktu sejak pembayaran dividen terakhir (pemeriksaan kebaruan)',
  'Latest dividend versus prior payments (one-off check)': 'Dividen terakhir dibanding pembayaran sebelumnya (pemeriksaan pembayaran tidak rutin)',
  'Change in annual yield versus change in dividend per share, latest completed fiscal year': 'Perubahan yield tahunan dibanding perubahan dividen per saham pada tahun fiskal terakhir',
  'Payout ratio (coverage check)': 'Rasio pembayaran dividen (pemeriksaan cakupan laba)',
  'Payout ratio': 'Rasio pembayaran dividen',
  'Comparable valuation metric for the target (P/E)': 'Metrik valuasi perusahaan yang dapat dibandingkan (P/E)',
  'Size of the frozen valid peer set': 'Jumlah perusahaan pembanding valid dalam kelompok yang ditetapkan',
  'Target P/E versus frozen peer median': 'P/E perusahaan dibanding median kelompok pembanding yang ditetapkan',
  'Target P/BV versus frozen peer median (cross-check)': 'P/BV perusahaan dibanding median kelompok pembanding (pemeriksaan silang)',
  'Target ROE minus frozen peer median ROE, latest fiscal year': 'Selisih ROE perusahaan dan median ROE pembanding pada tahun fiskal terakhir',
  'Current P/E versus the median of its own prior fiscal years': 'P/E saat ini dibanding median riwayat tahun fiskal perusahaan',
  'Last close versus its high over the past year': 'Harga penutupan terakhir dibanding harga tertinggi setahun terakhir',
  'Testing the strongest case against the claim': 'Menguji alasan tandingan terkuat terhadap klaim',
  'Establishing the claim': 'Memeriksa dasar klaim',
  'Looking for evidence against the claim': 'Mencari bukti yang melemahkan klaim',
  'supports the claim': 'mendukung klaim',
  'weakens the claim': 'melemahkan klaim',
  'is inconclusive': 'belum memberikan kesimpulan',
  'A yield at or above its own historical average supports the claim.': 'Yield yang sama atau lebih tinggi dari rata-rata riwayat perusahaan mendukung klaim.',
  'A positive P/E is required; zero or negative is not comparable.': 'P/E harus positif; nilai nol atau negatif tidak dapat dibandingkan.',
  'Opened by the previous result.': 'Dibuka berdasarkan hasil pemeriksaan sebelumnya.',
  'Testing the counter-case:': 'Menguji alasan tandingan:',
  'The next open check that establishes the claim.': 'Pemeriksaan dasar klaim berikutnya yang belum selesai.',
  'The next open check for evidence against it.': 'Pemeriksaan bukti pelemah berikutnya yang belum selesai.',
  'The investigation now asks:': 'Pemeriksaan kini menanyakan:',
  'All eligible checks are resolved.': 'Semua pemeriksaan yang dapat dijalankan telah selesai.',
  'Session time limit reached; reporting what was found so far.': 'Batas waktu sesi tercapai; laporan menggunakan temuan yang sudah tersedia.',
  'Claim is outside supported evidence contracts.': 'Klaim berada di luar cakupan pemeriksaan bukti yang didukung.',
  'No resolved company for this claim.': 'Perusahaan untuk klaim ini belum dapat diidentifikasi.',
  'No evidence contract covers this claim type.': 'Belum ada aturan pemeriksaan bukti untuk jenis klaim ini.',
  'Forward-looking claims about prices, returns, or future outcomes are outside available evidence.': 'Klaim mengenai harga, imbal hasil, atau hasil di masa depan berada di luar bukti yang tersedia.',
  'This kind of claim cannot be tested with Sectors company and market data.': 'Jenis klaim ini tidak dapat diuji dengan data perusahaan dan pasar dari Sectors.',
  'Peer-relative growth is not yet supported in this version.': 'Perbandingan pertumbuhan antarperusahaan belum didukung pada versi ini.',
  'revenue or net income growth not available': 'pertumbuhan pendapatan atau laba bersih tidak tersedia',
  'no reported quarters to anchor the base year': 'tidak ada laporan kuartal untuk menentukan tahun dasar',
  'no reported periods': 'tidak ada periode yang dilaporkan',
  'current P/E not comparable': 'P/E saat ini tidak dapat dibandingkan',
  'non-positive P/E is not comparable': 'P/E nol atau negatif tidak dapat dibandingkan',
  '52-week high or last close not reported': 'harga tertinggi 52 minggu atau penutupan terakhir tidak dilaporkan',
  'target ROE not reported': 'ROE perusahaan tidak dilaporkan',
  'revenue or net income missing': 'pendapatan atau laba bersih tidak tersedia',
  'trailing yield not reported': 'yield dividen 12 bulan terakhir tidak dilaporkan',
  'no dividend payments reported': 'tidak ada pembayaran dividen yang dilaporkan',
  'fewer than 3 dividend payments': 'pembayaran dividen kurang dari 3 kali',
  'non-positive prior dividends': 'dividen sebelumnya bernilai nol atau negatif',
  'payout ratio not reported': 'rasio pembayaran dividen tidak dilaporkan',
  'P/E not reported': 'P/E tidak dilaporkan',
  'peer median is not positive': 'median pembanding tidak positif',
  'no two consecutive completed years with both yield and dividend data': 'data yield dan dividen untuk dua tahun penuh berturut-turut tidak tersedia',
  'prior-period value is negative; growth rate is not meaningful': 'nilai periode sebelumnya negatif; tingkat pertumbuhan tidak bermakna',
  'prior-period value is zero': 'nilai periode sebelumnya nol',
  'denominator is zero or negative': 'penyebut bernilai nol atau negatif',
  'non-finite input': 'nilai masukan bukan angka terhingga',
  'annual net income growth': 'pertumbuhan laba bersih tahunan',
  'prior-year net income growth': 'pertumbuhan laba bersih tahun sebelumnya',
  'prior-quarter revenue growth YoY': 'pertumbuhan pendapatan kuartal sebelumnya dibanding tahun sebelumnya',
  'revenue growth YoY': 'pertumbuhan pendapatan dibanding tahun sebelumnya',
  'net income growth YoY': 'pertumbuhan laba bersih dibanding tahun sebelumnya',
  'annual revenue growth': 'pertumbuhan pendapatan tahunan',
  'net margin change': 'perubahan margin bersih',
  'trailing dividend yield': 'yield dividen 12 bulan terakhir',
  'historical average yield': 'rata-rata riwayat yield',
  'days since last dividend': 'hari sejak dividen terakhir',
  'latest dividend vs prior median': 'dividen terakhir dibanding median sebelumnya',
  'payout ratio': 'rasio pembayaran dividen',
  'valid peers': 'perusahaan pembanding valid',
  'P/E vs peer median': 'P/E dibanding median pembanding',
  'P/BV vs peer median': 'P/BV dibanding median pembanding',
  'prior three-year average ROE': 'rata-rata ROE tiga tahun sebelumnya',
  'ROE change': 'perubahan ROE',
  'yield change': 'perubahan yield',
  'dividend per share change': 'perubahan dividen per saham',
  'own historical median P/E': 'median riwayat P/E perusahaan',
  'current P/E': 'P/E saat ini',
  'P/E vs own history': 'P/E dibanding riwayat perusahaan',
  'last close': 'harga penutupan terakhir',
  'past-year high': 'harga tertinggi setahun terakhir',
  'distance from past-year high': 'selisih dari harga tertinggi setahun terakhir',
  'peer median ROE': 'median ROE pembanding',
  'ROE vs peer median': 'ROE dibanding median pembanding',
  'net income growth minus revenue growth': 'selisih pertumbuhan laba bersih dan pendapatan',
  'not investigated': 'belum diperiksa',
  'unavailable': 'tidak tersedia',
  'invalid': 'tidak valid',
  'stopped': 'dihentikan',
  'as of': 'per',
  'vs': 'dibanding',
  'peers:': 'pembanding:',
  'included:': 'digunakan:',
  'excluded:': 'dikecualikan:',
  'none': 'tidak ada',
  'n/a': 'tidak tersedia',
};

const patterns: Array<[RegExp, (...values: string[]) => string]> = [
  [/no data source for ([\w]+) in this version/g, (_, metric) => `tidak ada sumber data untuk ${metric} pada versi ini`],
  [/data retrieval failed:/g, () => 'pengambilan data gagal:'],
  [/Planner (.+?) failed \((.*?)\); using deterministic planner for this step\./g, (_, name, reason) => `Perencana ${name} mengalami kendala (${reason}); langkah ini menggunakan perencana deterministik.`],
  [/Rejected planner decision: (.*?)\. Using the deterministic planner for this step\./g, (_, reason) => `Keputusan perencana ditolak: ${reason}. Langkah ini menggunakan perencana deterministik.`],
  [/Planner wording rejected \((.*?)\); using neutral wording\./g, (_, reason) => `Redaksi perencana ditolak (${reason}); menggunakan redaksi netral.`],
  [/Growth more than ([\d.-]+) pp below the previous quarter weakens the claim\./g, (_, n) => `Pertumbuhan lebih dari ${n} poin persentase di bawah kuartal sebelumnya melemahkan klaim.`],
  [/Net income growth ([\d.-]+) pp or more below revenue growth weakens the claim\./g, (_, n) => `Pertumbuhan laba bersih ${n} poin persentase atau lebih di bawah pertumbuhan pendapatan melemahkan klaim.`],
  [/A base year that did not grow, together with growth of at least ([\d.-]+)% now, confirms a rebound\./g, (_, n) => `Tahun dasar yang tidak tumbuh, disertai pertumbuhan saat ini minimal ${n}%, mengonfirmasi pemulihan.`],
  [/A yield jump of ([\d.-]+)% or more, while dividend per share grew less than half as fast, confirms it\./g, (_, n) => `Lonjakan yield minimal ${n}%, sementara pertumbuhan dividen per saham kurang dari separuhnya, mengonfirmasi alasan tandingan ini.`],
  [/At least (\d+) valid peers are required, or the comparison is unavailable\./g, (_, n) => `Diperlukan minimal ${n} perusahaan pembanding valid; jika kurang, perbandingan tidak tersedia.`],
  [/only (\d+) valid peers; minimum(?: is)? (\d+)/g, (_, n, min) => `hanya ${n} perusahaan pembanding valid; minimal ${min}`],
  [/Lined up the checks for this claim under contract ([\w.-]+): (\d+) to establish it, (\d+) looking for evidence against it, and (\d+) testing the strongest opposing case\. Some open only if a result calls for them\./g, (_, id, required, counter, opposing) => `Pemeriksaan klaim menggunakan aturan ${id}: ${required} pemeriksaan dasar, ${counter} pemeriksaan bukti pelemah, dan ${opposing} pengujian alasan tandingan terkuat. Sebagian hanya dibuka jika hasil pemeriksaan memerlukannya.`],
  [/No budget left to follow up, so (\d+) further questions? stay unanswered:/g, (_, n) => `Batas pemeriksaan tercapai sehingga ${n} pertanyaan lanjutan belum terjawab:`],
  [/Only (\d+) required checks can still complete; contract needs (\d+)\./g, (_, n, min) => `Hanya ${n} pemeriksaan wajib yang masih dapat diselesaikan; aturan memerlukan ${min}.`],
  [/Tool budget of (\d+) reached with (\d+) checks open\./g, (_, limit, n) => `Batas ${limit} pemanggilan alat tercapai dengan ${n} pemeriksaan belum selesai.`],
];

const escaped = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
// One pass, longest phrases first: translated output is never translated again.
const phrases = new RegExp(`(?<![\\p{L}\\p{N}_])(?:${Object.keys(copy).sort((a, b) => b.length - a.length).map(escaped).join('|')})(?![\\p{L}\\p{N}_])`, 'gu');

export function localizeBackendCopy(message: string): string {
  let text = message;
  for (const [pattern, render] of patterns) text = text.replace(pattern, render);
  return text.replace(phrases, (phrase) => copy[phrase] ?? phrase);
}
