export const landingEnglish: Record<string, string> = {
  'Tentang produk': 'About the product',
  'Bukti sebelum keputusan': 'Evidence before decisions',
  'Lihat cara kerjanya': 'See how it works',
  'Contoh ilustrasi': 'Illustrative example',
  'Pilih contoh klaim': 'Select an example claim',
  'Valuasinya paling murah.': 'Its valuation is the cheapest.',
  'Harga pasti tembus 6.000.': 'The price will definitely reach 6,000.',
  'Pertumbuhan laba': 'Earnings growth',
  'PER vs pembanding': 'P/E vs peers',
  'Target harga': 'Price target',
  'Pada contoh ini, laba berubah dari 100 menjadi 120 pada periode pembanding yang sama.': 'In this example, earnings rise from 100 to 120 across comparable periods.',
  'Kenaikan laba sendiri belum membuktikan harga akan naik.': 'Earnings growth alone does not establish that the price will rise.',
  'PER contoh lebih rendah dari median pembanding, tetapi itu belum membuktikan bahwa saham ini paling murah.': 'The example P/E is below the peer median, but this does not establish that the stock is the cheapest.',
  'Perusahaan pembanding dan periode data perlu diperhatikan.': 'The peer selection and data periods matter.',
  'Data historis pada contoh ini tidak dapat memastikan harga saham di masa depan.': 'Historical data in this example cannot establish a future stock price.',
  'Prediksi harga bukan kepastian, meskipun sebagian alasan fundamentalnya didukung.': 'A price prediction is not a certainty, even when some fundamental arguments are supported.',
  'XYZ dan semua angka di sini adalah ilustrasi, bukan hasil pemeriksaan perusahaan nyata.': 'XYZ and all figures here are illustrative, not an investigation of a real company.',
  'Cara kerja': 'How it works',
  'Pertanyaan yang mungkin kamu punya.': 'Questions you might have.',
  'Apakah Counterpoint memberi rekomendasi beli atau jual?': 'Does Counterpoint recommend buying or selling?',
  'Tidak. Counterpoint memeriksa dukungan bukti terhadap klaim. Hasilnya bukan rekomendasi transaksi dan tidak menjamin harga akan naik atau turun.': 'No. Counterpoint checks the evidence supporting a claim. Results are not trading recommendations and do not guarantee that a price will rise or fall.',
  'Apakah semua klaim bisa diverifikasi?': 'Can every claim be verified?',
  'Tidak selalu. Prediksi harga atau klaim di luar cakupan data bisa tetap belum terverifikasi. Keterbatasan tersebut ditampilkan pada hasil pemeriksaan.': 'Not always. Price predictions or claims outside the data coverage may remain unverifiable. These limitations are shown in the investigation results.',
  'Bisa langsung pakai screenshot?': 'Can I use a screenshot?',
  'Bisa. Unggah PNG, JPEG, atau WebP hingga 4 MB. Teks hasil pembacaan bisa kamu edit sebelum diperiksa.': 'Yes. Upload a PNG, JPEG, or WebP up to 4 MB. You can edit the extracted text before investigating it.',
  'Apakah hasilnya bisa dibuka lagi?': 'Can I revisit the results?',
  'Bawa pesannya. Lihat apa yang didukung data sebelum menarik kesimpulan.': 'Bring the message. See what the data supports before drawing conclusions.',
  'Sebelum percaya': 'Before you believe',
  'narasinya,': 'the story,',
  'periksa buktinya.': 'check the evidence.',
  'Counterpoint membantu kamu melihat apakah klaim didukung data, apa yang melemahkannya, dan apa yang belum terbukti.': 'Counterpoint helps you see whether a claim is supported by data, what weakens it, and what remains unproven.',
  'Cek klaim sekarang': 'Check a claim now',
  'Contoh ilustrasi: satu pesan dipecah menjadi tiga klaim, dan setiap klaim dinilai dengan bukti.': 'Illustrative example: one message split into three claims, each assessed against evidence.',
  'XYZ menarik! Labanya naik 20% tahun ini, valuasinya paling murah. Harga pasti tembus 6.000!': 'XYZ looks great! Profit is up 20% this year, the valuation is the cheapest. The price will definitely break 6,000!',
  'Dicek ke laporan keuangan': 'Checked against financial statements',
  'Valuasi vs peer': 'Valuation vs peers',
  'Dibandingkan dengan median peer': 'Compared with the peer median',
  'Masa depan tidak ada di data': 'The future is not in the data',
  'Contoh tampilan hasil pemeriksaan': 'Example of an investigation result',
  'Pemeriksaan': 'Investigations',
  'Ditemukan 3 klaim utama dari pesan kamu.': 'Found 3 main claims in your message.',
  'Pesan yang kamu periksa': 'The message you checked',
  'Labanya naik 20% tahun ini.': 'Profit is up 20% this year.',
  'Didukung': 'Supported',
  'Sebagian': 'Partly',
  'Belum terverifikasi': 'Not yet verifiable',
  'FAQ': 'FAQ',
  'Cara kerja Counterpoint': 'How Counterpoint works',
  'Dari satu pesan,': 'From one message,',
  'sampai bukti yang bisa ditelusuri.': 'to evidence you can trace.',
  'Counterpoint memecah sebuah ajakan menjadi klaim yang bisa diuji, memeriksa bukti dari dua sisi, lalu menunjukkan dasar penilaiannya.': 'Counterpoint splits a pitch into claims that can be tested, checks the evidence on both sides, then shows what each assessment rests on.',
  'Pisahkan klaimnya.': 'Split the claims.',
  'Setiap alasan dalam satu pesan diperiksa secara terpisah.': 'Each reason in a message is checked on its own.',
  'Uji dua sisinya.': 'Test both sides.',
  'Cari apa yang mendukung klaim, sekaligus apa yang dapat melemahkannya.': 'Look for what supports a claim, and for what could weaken it.',
  'Buka dasar penilaiannya.': 'Open what the assessment rests on.',
  'Lihat sumber, periode, dan batas pemeriksaannya.': 'See the source, the period, and the limits of the check.',
  'XYZ menarik! Laba naik 20%, valuasi paling murah, harga pasti naik.': 'XYZ looks great! Profit up 20%, cheapest valuation, the price will surely rise.',
  'Laba naik 20%': 'Profit up 20%',
  'Valuasi paling murah': 'Cheapest valuation',
  'Harga pasti naik': 'Price will surely rise',
  'Menantang': 'Challenges',
  'ROE di bawah median peer': 'ROE below the peer median',
  'Kesimpulan': 'Conclusion',
  'Data & periode': 'Data & period',
  'Data Sectors': 'Sectors data',
  'Data apa yang dipakai?': 'What data does it use?',
  'Data perusahaan dari Sectors, seperti laporan keuangan, valuasi, dan perbandingan dengan perusahaan sejenis. Counterpoint tidak membaca berita atau opini analis, jadi klaim yang bergantung pada keduanya bisa tetap belum terverifikasi.': 'Company data from Sectors, such as financial statements, valuation and comparisons with similar companies. Counterpoint does not read news or analyst opinions, so claims that depend on them may stay unverified.',
  'Cara membaca hasil': 'Reading the result',
  'Labelnya singkat.': 'The label is short.',
  'Dasarnya bisa dibuka.': 'What it rests on is open.',
  'P/E di bawah median peer': 'P/E below the peer median',
  'Lihat angka utama, alasan tandingan, dan jejak pemeriksaannya dalam satu laporan.': 'See the key numbers, the counterpoint, and the trail of the check in one report.',
  'Contoh laporan, angka ilustrasi': 'Sample report, illustrative figures',
  'Contoh laporan klaim': 'Sample claim report',
  'Mendukung jika P/E minimal 10% di bawah median perusahaan pembanding.': 'Supports if the P/E is at least 10% below the peer median.',
  'Melemahkan jika ROE minimal 3 pp di bawah median perusahaan pembanding.': 'Weakens if the ROE is at least 3 pp below the peer median.',
  'Apakah valuasinya lebih murah karena ROE lebih rendah dari perusahaan pembanding?': 'Is it cheaper because it earns lower returns on equity than its peers?',
  'Apakah P/E ini normal bagi perusahaan ini sehingga tidak murah dibanding riwayatnya sendiri?': 'Is this P/E normal for this company, so it is not cheap by its own standards?',
  'Apakah valuasi rendah terjadi bersamaan dengan penurunan besar harga saham?': 'Does the low valuation coincide with a large fall in the share price?',
  'Di laporan asli, setiap angka bisa dibuka untuk melihat sumber data Sectors, periodenya, dan daftar perusahaan pembanding yang dipakai.': 'In a real report, every number opens to show its Sectors data source, its period, and the list of peer companies used.',
  'Ambil P/E perusahaan': 'Get the company P/E',
  'Tetapkan perusahaan pembanding': 'Fix the peer set',
  'Bandingkan P/E dengan median pembanding': 'Compare the P/E with the peer median',
  'Cek silang P/BV dengan median pembanding': 'Cross-check the P/BV against the peer median',
  'Uji ROE dibanding perusahaan pembanding': 'Test ROE against the peers',
  'Uji P/E dibanding riwayatnya sendiri': 'Test the P/E against its own history',
  'Uji penurunan harga dari puncak 52 minggu': 'Test the fall from the 52-week high',
  'P/E vs median pembanding': 'P/E vs peer median',
  'ROE vs median pembanding': 'ROE vs peer median',
  'P/BV vs median pembanding': 'P/BV vs peer median',
  'Pembanding yang valid': 'Valid peers',
  'Siap cek sendiri?': 'Ready to check one yourself?',
  'Ada ajakan saham': 'Got a stock pitch',
  'yang ingin kamu cek?': 'you want to check?',
  'Cek data, bukan sekadar ajakan.': 'Check the data, not just the pitch.',
};
