export const landingEnglish: Record<string, string> = {
  'Tentang produk': 'About the product',
  'Kenapa Counterpoint': 'Why Counterpoint',
  'Buka aplikasi': 'Open the app',
  'Bukti sebelum keputusan': 'Evidence before decisions',
  'Sebelum ikut FOMO,': 'Before you follow the hype,',
  'cek dulu klaimnya.': 'check the claims.',
  'Ajakan saham bisa terdengar meyakinkan. Counterpoint membantu kamu melihat apakah alasannya didukung data, apa yang melemahkannya, dan apa yang belum terbukti.': 'A stock pitch can sound convincing. Counterpoint helps you see whether the reasoning is supported by data, what weakens it, and what remains unproven.',
  'Cek klaim saham': 'Check a stock claim',
  'Lihat cara kerjanya': 'See how it works',
  'Bukti pendukung dan pelemah. Satu laporan yang bisa ditelusuri.': 'Supporting and opposing evidence. One traceable report.',
  'Dari pesan ke pemeriksaan': 'From a message to an investigation',
  'Contoh ilustrasi': 'Illustrative example',
  'Pesan yang kamu terima': 'A message you receive',
  'XYZ menarik! Labanya naik 20%, valuasinya paling murah. Harga pasti tembus 6.000!': 'XYZ looks great! Earnings are up 20%, its valuation is the cheapest. The price will definitely reach 6,000!',
  'Satu pesan. Tiga klaim berbeda.': 'One message. Three distinct claims.',
  'Pilih contoh klaim': 'Select an example claim',
  'Labanya naik 20%.': 'Earnings are up 20%.',
  'Valuasinya paling murah.': 'Its valuation is the cheapest.',
  'Harga pasti tembus 6.000.': 'The price will definitely reach 6,000.',
  'Pertumbuhan laba': 'Earnings growth',
  'PER vs pembanding': 'P/E vs peers',
  'Target harga': 'Price target',
  'Pada contoh ini, laba berubah dari 100 menjadi 120 pada periode pembanding yang sama.': 'In this example, earnings rise from 100 to 120 across comparable periods.',
  'Kenaikan laba sendiri belum membuktikan harga akan naik.': 'Earnings growth alone does not establish that the price will rise.',
  'PER contoh lebih rendah dari median pembanding, tetapi itu belum membuktikan bahwa saham ini paling murah.': 'The example P/E is below the peer median, but this does not establish that the stock is the cheapest.',
  'Perusahaan pembanding dan periode data perlu diperhatikan.': 'The peer selection and data periods matter.',
  'Data historis pada contoh ini tidak dapat memastikan harga saham di masa depan.': 'Historical data in this example cannot establish a future stock price.',
  'Prediksi harga bukan kepastian, meskipun sebagian alasan fundamentalnya didukung.': 'A price prediction is not a certainty, even when some fundamental arguments are supported.',
  'XYZ dan semua angka di sini adalah ilustrasi, bukan hasil pemeriksaan perusahaan nyata.': 'XYZ and all figures here are illustrative, not an investigation of a real company.',
  'Prinsip Counterpoint': 'Counterpoint principles',
  'Per klaim': 'Claim by claim',
  'Pisahkan alasan dalam satu pesan.': 'Separate the arguments in a message.',
  'Dua sisi': 'Both sides',
  'Uji pendukung sekaligus tandingannya.': 'Test support and the counter-case.',
  'Bisa ditelusuri': 'Traceable',
  'Baca bukti, periode, dan batasannya.': 'Read the evidence, periods, and limitations.',
  'Kenapa kami membangun Counterpoint': 'Why we built Counterpoint',
  'Beri ruang untuk berpikir, sebelum ikut percaya.': 'Make room to think before you believe.',
  'Kami ingin menciptakan jeda antara menerima ajakan saham dan mengambil keputusan. Jeda untuk memeriksa, membandingkan, dan memahami ketidakpastian.': 'We want to create a pause between receiving a stock pitch and making a decision. Time to investigate, compare, and understand uncertainty.',
  'Pesannya datang dari mana saja.': 'The messages come from everywhere.',
  'Stockbit, X, Telegram, atau grup percakapan. Ada angka, cerita pertumbuhan, dan target harga dalam satu pesan.': 'Stockbit, X, Telegram, or a group chat. Numbers, growth narratives, and price targets can share the same message.',
  'Alasan yang terdengar kuat belum tentu lengkap.': 'Convincing reasoning can still be incomplete.',
  'Angka bisa memakai periode yang berbeda. Pembanding bisa kurang tepat. Sebagian prediksi belum bisa dibuktikan dengan data yang ada.': 'Figures may cover different periods. Peers may be unsuitable. Some predictions cannot be established with the available data.',
  'Jadi, apakah ajakan ini didukung bukti?': 'So, is this pitch supported by evidence?',
  'Counterpoint memecah klaimnya, memeriksa data Sectors, lalu menguji alasan yang dapat menyanggahnya. Kamu mendapat hasil beserta dasar dan batasannya.': 'Counterpoint breaks down the claims, checks Sectors data, and tests the case against them. You get results with their basis and limitations.',
  'Cara kerja': 'How it works',
  'Pesan masuk. Bukti yang bicara.': 'A message comes in. The evidence speaks.',
  'Tiga langkah untuk memahami apa yang sebenarnya didukung oleh data.': 'Three steps to understand what the data actually supports.',
  'Masukkan pesan atau screenshot': 'Add a message or screenshot',
  'Tempel ajakan saham, atau unggah screenshot. Baca dan edit teksnya sebelum memulai pemeriksaan.': 'Paste a stock pitch or upload a screenshot. Read and edit the text before starting the investigation.',
  'Ikuti pemeriksaan dari dua sisi': 'Follow the investigation from both sides',
  'Lihat klaim yang diuji, data yang diperiksa, dan alasan tandingannya. Buka alur agent untuk menelusuri setiap langkah.': 'See the claims under test, the data being checked, and the counter-case. Open the agent workflow to trace each step.',
  'Baca hasil beserta batasannya': 'Read results with their limitations',
  'Lihat klaim yang didukung, dilemahkan, atau belum dapat diverifikasi. Buka bukti pendukungnya dan simpan akses lewat riwayat.': 'See which claims are supported, weakened, or still unverifiable. Open the evidence and revisit results through history.',
  'Transparansi sejak awal': 'Transparency from the start',
  'Jangan berhenti pada label. Lihat dasar penilaiannya.': 'Go beyond the label. Read the basis for the assessment.',
  'Hasil pemeriksaan seharusnya bisa dijelaskan. Counterpoint menampilkan dasar penilaian dan hal yang masih belum diketahui.': 'An investigation result should be explainable. Counterpoint shows the basis for its assessment and what remains unknown.',
  'Coba pemeriksaannya': 'Try an investigation',
  'Sumber dan periode terlihat': 'Visible sources and periods',
  'Buka sumber bukti, periode metrik, dan waktu pengambilan data pada laporan.': 'Open evidence sources, metric periods, and data retrieval times in the report.',
  'Penilaian punya aturan': 'Assessments follow rules',
  'Perhitungan dan hasil penilaian mengikuti aturan pemeriksaan. Model bahasa membantu menafsirkan pesan dan menyusun penjelasan.': 'Calculations and assessments follow investigation rules. Language models help interpret the message and compose explanations.',
  'Alasan tandingan ikut diuji': 'The counter-case is tested too',
  'Pemeriksaan mencari bukti pendukung sekaligus alasan yang dapat melemahkan klaim.': 'The investigation looks for supporting evidence and reasons that could weaken the claim.',
  'Ketidakpastian tetap terlihat': 'Uncertainty stays visible',
  'Data yang hilang, batas pemeriksaan, dan penggunaan data sintetis untuk demo diberi keterangan.': 'Missing data, investigation limits, and the use of synthetic demo data are labelled.',
  'Sebelum mencoba': 'Before you try',
  'Pertanyaan yang mungkin kamu punya.': 'Questions you might have.',
  'Apakah Counterpoint memberi rekomendasi beli atau jual?': 'Does Counterpoint recommend buying or selling?',
  'Tidak. Counterpoint memeriksa dukungan bukti terhadap klaim. Hasilnya bukan rekomendasi transaksi dan tidak menjamin harga akan naik atau turun.': 'No. Counterpoint checks the evidence supporting a claim. Results are not trading recommendations and do not guarantee that a price will rise or fall.',
  'Apakah semua klaim bisa diverifikasi?': 'Can every claim be verified?',
  'Tidak selalu. Prediksi harga atau klaim di luar cakupan data bisa tetap belum terverifikasi. Keterbatasan tersebut ditampilkan pada hasil pemeriksaan.': 'Not always. Price predictions or claims outside the data coverage may remain unverifiable. These limitations are shown in the investigation results.',
  'Bisa langsung pakai screenshot?': 'Can I use a screenshot?',
  'Bisa. Unggah PNG, JPEG, atau WebP hingga 4 MB. Teks hasil pembacaan bisa kamu edit sebelum diperiksa.': 'Yes. Upload a PNG, JPEG, or WebP up to 4 MB. You can edit the extracted text before investigating it.',
  'Apakah hasilnya bisa dibuka lagi?': 'Can I revisit the results?',
  'Bisa lewat tab Riwayat pada browser yang sama. Riwayat belum tersinkron antarperangkat; kamu juga bisa menyimpan tautan laporannya.': 'Yes, through History in the same browser. History does not yet sync across devices; you can also save the report link.',
  'Mulai dari satu pesan': 'Start with one message',
  'Ada ajakan saham yang ingin kamu cek?': 'Have a stock pitch you want to check?',
  'Bawa pesannya. Lihat apa yang didukung data sebelum menarik kesimpulan.': 'Bring the message. See what the data supports before drawing conclusions.',
};
