/**
 * Hand-written names people use for listed companies that neither the legal name, Wikidata
 * nor the company website covers. Add to this list freely; it is merged into the index at start.
 * Keys are IDX tickers. A name shared by two companies makes the user choose between them.
 */
export const COMPANY_ALIASES: Record<string, string[]> = {
  WIFI: ['Surge', 'Surge Group'],
  AMRT: ['Alfamart'],
  MIDI: ['Alfamidi'],
  BBCA: ['BCA', 'Bank BCA'],
  BBRI: ['BRI', 'Bank BRI'],
  BMRI: ['Mandiri', 'Bank Mandiri'],
  BBNI: ['BNI', 'Bank BNI'],
  BBTN: ['BTN', 'Bank BTN'],
  BRIS: ['BSI', 'Bank Syariah Indonesia'],
  ARTO: ['Bank Jago'],
  BJBR: ['BJB', 'Bank BJB'],
  TLKM: ['Telkom', 'Telkom Indonesia'],
  ISAT: ['Indosat', 'Indosat Ooredoo'],
  EXCL: ['XL', 'XL Axiata', 'XLSmart'],
  MTEL: ['Mitratel'],
  GOTO: ['GoTo', 'Gojek', 'Tokopedia'],
  BUKA: ['Bukalapak'],
  ASII: ['Astra'],
  UNVR: ['Unilever'],
  ICBP: ['Indomie'],
  INDF: ['Indofood'],
  HMSP: ['Sampoerna'],
  GGRM: ['Gudang Garam'],
  ANTM: ['Antam'],
  INCO: ['Vale', 'Vale Indonesia'],
  PTBA: ['Bukit Asam'],
  KLBF: ['Kalbe', 'Kalbe Farma'],
  SIDO: ['Sido Muncul'],
  ACES: ['Ace Hardware'],
  ERAA: ['Erajaya'],
  CPIN: ['Charoen Pokphand'],
  JPFA: ['Japfa'],
  SMGR: ['Semen Indonesia', 'SIG'],
  PGAS: ['PGN'],
  JSMR: ['Jasa Marga'],
  MYOR: ['Mayora'],
  SILO: ['Siloam'],
  HEAL: ['Hermina'],
};
