/**
 * Builds src/entity/company-index.data.ts: every company Sectors lists, with the aliases and
 * websites Wikidata records for its IDX ticker. Costs one Sectors call per 200 companies (5 for
 * the whole exchange) and one Wikidata query. Re-run when companies list or change names.
 *
 *   pnpm --filter @counterpoint/api build-company-index
 */
import { existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { CompanyRecord } from '../src/entity/company-index';

const envFile = resolve(__dirname, '../../../.env');
if (existsSync(envFile)) process.loadEnvFile(envFile);

const OUT = resolve(__dirname, '../src/entity/company-index.data.ts');
const USER_AGENT = 'Counterpoint/0.1 (company index build; IDX hackathon project)';
const PAGE = 200;

interface SectorsPage {
  results: { symbol: string; company_name: string }[];
  pagination: { has_next: boolean; next_offset: number | null };
}

async function sectorsCompanies(): Promise<{ ticker: string; name: string }[]> {
  const apiKey = process.env.SECTORS_API_KEY;
  if (!apiKey) throw new Error('SECTORS_API_KEY is not set');
  const base = (process.env.SECTORS_BASE_URL ?? 'https://api.sectors.app/v2').replace(/\/$/, '');
  const out: { ticker: string; name: string }[] = [];
  let offset: number | null = 0;
  while (offset !== null) {
    const res = await fetch(`${base}/companies/?limit=${PAGE}&offset=${offset}`, { headers: { Authorization: apiKey, Accept: 'application/json' } });
    if (!res.ok) throw new Error(`Sectors ${res.status} at offset ${offset}`);
    const page = (await res.json()) as SectorsPage;
    out.push(...page.results.map((c) => ({ ticker: c.symbol.replace(/\.JK$/, ''), name: c.company_name })));
    offset = page.pagination.has_next ? page.pagination.next_offset : null;
  }
  return out;
}

const SPARQL = `
SELECT ?ticker ?itemLabel (GROUP_CONCAT(DISTINCT ?alias; separator="\\u001f") AS ?aliases)
       (GROUP_CONCAT(DISTINCT STR(?site); separator="\\u001f") AS ?sites) WHERE {
  ?exchange rdfs:label "Indonesia Stock Exchange"@en .
  ?item p:P414 ?listing . ?listing ps:P414 ?exchange ; pq:P249 ?ticker .
  OPTIONAL { ?item skos:altLabel ?alias . FILTER(LANG(?alias) IN ("en", "id")) }
  OPTIONAL { ?item wdt:P856 ?site . }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "id,en". }
} GROUP BY ?ticker ?itemLabel`;

interface Binding {
  ticker: { value: string };
  itemLabel?: { value: string };
  aliases?: { value: string };
  sites?: { value: string };
}

async function wikidataCompanies(): Promise<Map<string, { aliases: string[]; websites: string[] }>> {
  const url = `https://query.wikidata.org/sparql?query=${encodeURIComponent(SPARQL)}`;
  const res = await fetch(url, { headers: { Accept: 'application/sparql-results+json', 'User-Agent': USER_AGENT } });
  if (!res.ok) throw new Error(`Wikidata ${res.status}`);
  const bindings = ((await res.json()) as { results: { bindings: Binding[] } }).results.bindings;
  const split = (v?: { value: string }) => (v?.value ? v.value.split('\u001f') : []);
  const out = new Map<string, { aliases: string[]; websites: string[] }>();
  for (const b of bindings) {
    const ticker = b.ticker.value.toUpperCase().replace(/^.*:/, '').replace(/\.JK$/, '').trim();
    if (!/^[A-Z]{4}$/.test(ticker)) continue;
    const label = b.itemLabel?.value;
    const entry = out.get(ticker) ?? { aliases: [], websites: [] };
    if (label && !/^Q\d+$/.test(label)) entry.aliases.push(label);
    entry.aliases.push(...split(b.aliases));
    entry.websites.push(...split(b.sites));
    out.set(ticker, entry);
  }
  return out;
}

async function main() {
  const [listed, wikidata] = await Promise.all([sectorsCompanies(), wikidataCompanies()]);
  const records: CompanyRecord[] = listed
    .map(({ ticker, name }) => {
      const extra = wikidata.get(ticker);
      const aliases = [...new Set((extra?.aliases ?? []).map((a) => a.trim()))].filter((a) => a && a.toUpperCase() !== ticker && a !== name);
      const websites = [...new Set(extra?.websites ?? [])];
      return { ticker, name, ...(aliases.length ? { aliases } : {}), ...(websites.length ? { websites } : {}) };
    })
    .sort((a, b) => a.ticker.localeCompare(b.ticker));

  const lines = records.map((r) => `  ${JSON.stringify(r)},`);
  writeFileSync(
    OUT,
    [
      '/* eslint-disable */',
      `// Generated by scripts/build-company-index.ts on ${new Date().toISOString().slice(0, 10)} from Sectors and Wikidata. Do not edit;`,
      '// add nicknames to company-aliases.ts instead.',
      "import type { CompanyRecord } from './company-index';",
      '',
      'export const COMPANY_RECORDS: CompanyRecord[] = [',
      ...lines,
      '];',
      '',
    ].join('\n'),
  );
  const withAliases = records.filter((r) => r.aliases || r.websites).length;
  console.log(`Wrote ${records.length} companies (${withAliases} with Wikidata aliases or websites) to ${OUT}`);
}

main().catch((err) => {
  console.error((err as Error).message);
  process.exit(1);
});
